### ISSUE TITLE
Attempted import error: 'react-canvas-js' does not contain a default export

### ISSUE THREAD

**Issue by MichaelZelensky** [shalomsam/react-canvas-js#8]
1. install 
$ npm install --save react-canvas-js

2. then in App.js: 
import Canvas from 'react-canvas-js'

3. See react build error
Attempted import error: 'react-canvas-js' does not contain a default export (imported as 'Canvas').

**Comment by shalomsam** [comment]
@MichaelZelensky - Hey thanks for raising an issue. Try importing it like so in App.js - 
`import { Canvas } from  'react-canvas-js'`

**Comment by shalomsam** [comment]
@MichaelZelensky - you can checkout examples out here - https://shalomsam.github.io/react-canvas-js/

**Comment by ViggoV** [comment]
You should probably update the readme then. The example given there clearly imports it as default: `import Canvas from 'react-canvas-js'`. Also, the options prop passed in that example is an array when it should be an object.
